# Docker file

# 1. Build Stage
FROM eclipse-temurin:17-jre-alpine

# 2. WORK DIR 설정
WORKDIR /PROD-IOT

# 3. 권한 설정
chmod 777 build/libs/*.jar

# 4. 빌드 된 jar 파일 복사
COPY build/libs/*.jar  prod-iot.jar

# 5. 컨테이너 포트 노출
EXPOSE 7070

# 6. 애플리케이션 실행 명령어
ENTRYPOINT ["java" , "-jar", "prod-iot.jar"]